version: '3.4'

services:
  webapinetcore:
    image: webapinetcore:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile   
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ProfileName=Development
    - ASPNETCORE_URLS=http://0.0.0.0:80
    - identityUrl=http://webapinetcore
    ports:
      - "8090:80"      